### ISSUE TITLE
How to sign in?

### ISSUE THREAD

**Issue by Ekobasher** [felipefrancisco/pokemon-go-map#18]
It may be really obvious and I might just be going blind but I don't see any way to "sign up" so I can put in pokemon locations

**Comment by Ekobasher** [comment]
<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/20521943/16924137/d38262fa-4d71-11e6-97d1-ef09d6815283.PNG">

**Comment by felipefrancisco** [comment]
Hey @Ekobasher, can you try again, please? Just made some modifications :)

**Comment by Pramaxis** [comment]
I can't sing in either. I tested it with Vivaldi 1.2.4 (Crome-Engin) and Firefox 43.
-Select place
-Select "sing in"
-Select Google-Acc
-Acc-Window closed
-Nothing happens / Can't work

**Comment by felipefrancisco** [comment]
@Pramaxis  @Ekobasher please, try cleaning the cache. I've deployed a fix during this morning, it should be working now. Thanks for reporting.

**Comment by felipefrancisco** [comment]
@Ekobasher I've noticed that in the right sidebar there are no visible pokemon, it seems that the images are not loading there, isnt this a local issue?

**Comment by Pramaxis** [comment]
@felipefrancisco Sorry but I still can't login now. I cleared the cache and even tried in IE and Opera but it is always the same result. Do we need flash for this service?

**Comment by felipefrancisco** [comment]
@Pramaxis the sign in side bar appears but the buttons don't? Or the sidebar just don't show up? Or do you click the sign in button and nothing happens?

**Comment by Pramaxis** [comment]
In IE, I hit the button, nothing happens.
In Opera, Vivaldi and Chromeium I hit the button and the window disappear instantiations. 
In FF, The window appears but if I select my Google account it closes without asking for permissions.

**Comment by felipefrancisco** [comment]
Thanks mate! Will solve this as soon as I get home. What IE version by the way?

**Comment by Pramaxis** [comment]
11.0.9600 /Last @Win7
